version: '2'
services:
  master:
    image: rancher/server
    ports:
      - "8080:8080"
    depends_on:
        - mysql
    environment:
      - db-host=mysql
      - db-port=3306
      - db-user=root
      - db-pass=root
      - db-name=cattle

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cattle

  fpm:
    build: ha-manager
    container_name: ha-manager
    volumes:
      - ./ha-manager:/ha-manager/
      - ~/data/ssh:/root/.ssh
      - ~/.composer:/root/.composer
